text_aligment/config/routes.rb
Rails.application.routes.draw do

  root 'texts#index'
  resources :texts do
    member do
      get :compare
      get :align
      post :update_alignment
    end
  end

end

text_aligment/app/models/correct_paragraph_alignment.rb
class CorrectParagraphAlignment < ActiveRecord::Base
  belongs_to :text

  serialize :native_paragraph_positions, Array
  serialize :foreign_paragraph_positions, Array

  structure do
    native_paragraph_positions :text
    foreign_paragraph_positions :text

    timestamps
  end
end

text_aligment/app/models/text.rb
class Text < ActiveRecord::Base
  validates :native, presence: true
  validates :foreign, presence: true

  has_many :correct_paragraph_alignments

  structure do
    native :text
    foreign :text

    timestamps
  end

  def paragraph_alignment_index_for(paragraph)
    alignment = if paragraph.class == Alignment::NativeParagraph
      correct_paragraph_alignments.detect{ |al| al.native_paragraph_positions.include?(paragraph.position.to_s) }
    else
      correct_paragraph_alignments.detect{ |al| al.foreign_paragraph_positions.include?(paragraph.position.to_s) }
    end
    correct_paragraph_alignments.pluck(:id).sort.index alignment.try(:id)
  end

  def aligned_paragraphs(strategy = :blind)
    alignment_runner(strategy).aligned_paragraphs
  end

  def native_paragraphs
    @native_paragraphs ||= native.split("\n").select(&:present?).map.with_index do |content, index|
      Alignment::NativeParagraph.new({ content: content, position: index + 1 })
    end
  end

  def foreign_paragraphs
    @foreign_paragraphs ||= foreign.split("\n").select(&:present?).map.with_index do |content, i|
      Alignment::ForeignParagraph.new({ content: content, position: i + 1})
    end
  end

  def max_paragraphs
    [native_paragraphs.length, foreign_paragraphs.length].max
  end

  def min_paragraphs
    [native_paragraphs.length, foreign_paragraphs.length].min
  end

  def alignment_runner(strategy = :blind)
    "Alignment::Strategy::#{strategy.to_s.camelcase}".constantize.new(self)
  end
end

text_aligment/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

text_aligment/app/controllers/texts_controller.rb
class TextsController < ApplicationController
  expose(:texts)
  expose(:text, attributes: :text_attributes)

  def index

  end

  def create
    text.save!
    redirect_to texts_path
  end

  def update
    text.save!
    redirect_to texts_path
  end

  def update_alignment
    text = Text.find(params[:id])
    params.permit!
    native_paragraphs_by_group = {}
    params[:native_paragraph_group].each_pair do |paragraph_position, group_number|
      native_paragraphs_by_group[group_number] ||= []
      native_paragraphs_by_group[group_number] << paragraph_position
    end

    foreign_paragraphs_by_group = {}
    params[:foreign_paragraph_group].each_pair do |paragraph_position, group_number|
      foreign_paragraphs_by_group[group_number] ||= []
      foreign_paragraphs_by_group[group_number] << paragraph_position
    end

    text.correct_paragraph_alignments.destroy_all
    (foreign_paragraphs_by_group.keys + native_paragraphs_by_group.keys).uniq.each do |group|
      text.correct_paragraph_alignments.create!(
        native_paragraph_positions: native_paragraphs_by_group[group] || [],
        foreign_paragraph_positions: foreign_paragraphs_by_group[group] || [],
      )
    end
    
    redirect_to :back
  end

  def text_attributes
    params.require(:text).permit(:native, :foreign)
  end
end

text_aligment/app/helpers/application_helper.rb
module ApplicationHelper
end

text_aligment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextAligment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

text_aligment/app/views/texts/_form.html.slim
= form_for text do |f|
  .field-left
    = f.label :native
    br
    = f.text_area :native, rows: 30
  .field-right
    = f.label :foreign
    br
    = f.text_area :foreign, rows: 30
  .field= f.submit

text_aligment/app/views/texts/align.html.slim
= form_tag update_alignment_text_path(text) do
  table.paragraphs-comparison
    - position_before = 0
    - text.max_paragraphs.times do |i|
      - native_paragraph = text.native_paragraphs[i]
      - foreign_paragraph = text.foreign_paragraphs[i]
      tr.paragraph-comparison
        td[style="text-align: right"]
          = i + 1
          | .
        td.native-paragraph= native_paragraph.try(:content)
        td.grouping
          - if native_paragraph.present?
            = number_field_tag "native_paragraph_group[#{native_paragraph.position}]", text.paragraph_alignment_index_for(native_paragraph) || i, class: 'native-paragraph-group paragraph-group'
          - else
            .blank-field

          '

          - if foreign_paragraph.present?
            = number_field_tag "foreign_paragraph_group[#{foreign_paragraph.position}]", text.paragraph_alignment_index_for(foreign_paragraph) || i, class: 'foreign-paragraph-group paragraph-group'
          - else
            .blank-field
        td.foreign-paragraph= foreign_paragraph.try(:content)
  = submit_tag 'update_alignment'
javascript:
  window.groupingColors = #{{ (0..text.max_paragraphs).map{ [rand(255), rand(255), rand(255)] }.to_json }};

coffee:
  $('tr.paragraph-comparison').on 'mouseenter', (e)->
    colorizeGroups(e, 'green')

text_aligment/app/views/texts/compare.html.slim
- aligned_paragraphs = text.aligned_paragraphs(:manual)

= text.native_paragraphs.first.aligned_paragraphs
/ table.paragraphs-comparison
/   - position_before = 0
/   - text.max_paragraphs.times do |i|
/     - native_paragraph = text.native_paragraphs[i]
/     - foreign_paragraph = text.foreign_paragraphs[i]
/     tr.paragraph-comparison[style="color:#{aligned_paragraph.position - position_before == 1 ? "black" : "red"}"]
/       td[style="text-align: right" data-aligned-paragraph=native_paragraph.aligned_paragraph(:manual).position ]
/         = aligned_paragraph.position
/         | .
/       td[style="text-align: right"]
/         | N
/         = aligned_paragraph.native_paragraphs[i].try(:position)
/         | .
/       td[style="text-align: right"]
/         | F
/         = aligned_paragraph.foreign_paragraphs[i].try(:position)
/         | .
/       td.native-paragraph
/         = aligned_paragraph.native_paragraphs[i].try(:content)
/       td.paragraph-percents
/       td.foreign-paragraph
/         = aligned_paragraph.foreign_paragraphs[i].try(:content)
/     - position_before = aligned_paragraph.position
= text.native_paragraphs.size
| \
= text.foreign_paragraphs.size
javascript:
  var paragraphComparison = #{{ aligned_paragraphs.to_json }};
  new TextComparator(paragraphComparison);

text_aligment/app/views/texts/edit.html.slim
=render 'form'

text_aligment/app/views/texts/index.html.slim
h1 Texts

= link_to 'New', new_text_path

table
  thead: tr
    th LT
    th EN
    th
  tbody
    - texts.each do |text|
      tr
        td= truncate(text.native, length: 100)
        td= truncate(text.foreign, length: 100)
        td
          = link_to 'Edit', edit_text_path(text)
          '  |
          = link_to 'Compare', compare_text_path(text)
          '  |
          = link_to 'Align', align_text_path(text)

text_aligment/app/views/texts/new.html.slim
= render 'form'