signalai2/config/routes.rb
Rails.application.routes.draw do

  resources :signals_collections do
    member do
      get :chart
    end
  end

  root 'signals_collections#index'

end

signalai2/app/models/signals_collection.rb
class SignalsCollection < ActiveRecord::Base
  serialize :signals, Array
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => /\Atext\/.*\Z/

  structure do
    url :string
    file_file_name :string
    file_content_type :string
    file_file_size :integer
    file_updated_at :datetime
    signals :text
    timestamps
  end

  def signals_data(noise = [])
    return @signals_data unless @signals_data.nil?

    require 'csv'
    @signals_data = {}
    return @signals_data if file.path.blank?

    noise_index = 0
    CSV.parse(File.read(file.path), { headers: true }) do |row|
      @signals_data[row.to_hash.values.first] = row.to_hash.values.last.to_f
      @signals_data[row.to_hash.values.first] += noise[noise_index].to_f
      noise_index += 1
    end
    @signals_data
  end

  def signals(options = {})
    @signals ||= {}
    @signals[options.to_json] ||= SignalsTransformer.new(signals_data, options)
  end
end

signalai2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

signalai2/app/controllers/signals_collections_controller.rb
class SignalsCollectionsController < ApplicationController
  expose(:signals_collections)
  expose(:signals_collection)
  expose(:signals){ signals_collection.signals.formated }
  expose(:signals_collection_params){ params.require(:signals_collection).permit(:file, :url) }
  expose(:brawler){ Brawler.new(signals_collection.signals.formated) }
  expose(:min_random){ (params[:min_random] || -1.0).to_f }
  expose(:max_random){ (params[:max_random] || 1.0).to_f }
  expose(:noise_type){ params[:noise_type] || 'random_scope' }
  expose(:ck_noise_interval_from){ params[:ck_noise_interval_from].presence || 0 }
  expose(:ck_noise_interval_till){ params[:ck_noise_interval_till].presence || 0 }
  expose(:ck_noise_items){
    (ck_noise_interval_from.to_i..ck_noise_interval_till.to_i).to_a
  }
  expose(:ck_noise){
    noise.map.with_index do |noise_value, i|
      ck_noise_items.include?(i) ? noise_value : 1.0
    end
  }
  expose(:noise){
    case noise_type
      when 'random_scope'
        brawler.random(min_random, max_random)
      when 'brownian'
        brawler.brownian
    end
  }

  expose(:filter_ck_list){ (params[:filter_ck_list] || ["80"]).map(&:to_i) }

  expose(:default_chart_options) {
    {
      library: {
        dataOpacity: 0.0,
        fontSize: '15px',
        vAxis: {
          textStyle: {fontSize: '17px;'}
        },
        hAxis: {
          textStyle: {fontSize: '17px;'}
        }
      },
      height: '750px',
      colors: ['black'],
      discrete: true
    }
  }

  def create
    SignalsCollection.create!(signals_collection_params)
    redirect_to signals_collections_url
  end
end

signalai2/app/helpers/application_helper.rb
module ApplicationHelper
  def hz_from_k(k, signals = signals_collection.signals)
    delta = (signals.formated.keys.last.to_time - signals.formated.keys.first.to_time).to_i
    k.to_f / delta
  end

  def human_hz_from_k(k, signals = signals_collection.signals)
    hz = hz_from_k(k, signals)
    mesures = %w(m µ n)
    mesure_index = 0
    hz *= 1000
    while hz < 1 and mesures[mesure_index + 1].present?
      hz *= 1000
      mesure_index += 1
    end
    mesure = mesures[mesure_index] || mesures.last
    "#{hz.round(2)} #{mesure}Hz"
  end

  def measure_from_k(k, signals)
  end

  def multiplier_for_mesure_from_k(k, signals)
    multiplier = 1
    while hz < 1 and mesures[mesure_index + 1].present?
      multiplier *= 1000
      mesure_index += 1
    end
  end
end

signalai2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script>
    var Chartkick = {"language": "lt"};
  </script>
  <%= javascript_include_tag "//www.google.com/jsapi" %>
  <script>
    google.load('visualization', '1', {'packages':['corechart'], 'language': 'lt'});
  </script>

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

signalai2/app/views/signals_collections/_form.html.slim
= form_for(signals_collection) do |f|
  - if signals_collection.errors.any?
    #error_explanation
      h2
        = pluralize(signals_collection.errors.count, "error")
        |  prohibited this signals collection from being saved:

      ul
        - signals_collection.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :url
    '
    = f.url_field :url

  .field
    = f.label :file
    '
    = f.file_field :file

  .actions= f.submit

signalai2/app/views/signals_collections/_hz_noise_charts.html.slim
= line_chart [\
    {\
      name: 'original',\
      data: signals_collection.signals.formated\
    },\
    {\
      name: 'fourier + ck noise',\
      data: signals_collection.signals(ck_noise: ck_noise).fourier\
    }\

  ], default_chart_options.merge(colors: ['black', 'red'])

= line_chart [\
    {\
      name: 'Užtriukšmintas signalas',\
      data: signals_collection.signals(ck_noise: ck_noise).fourier\
    },\
    {\
      name: 'Originalus signalas',\
      data: signals_collection.signals.formated\
    }\
  ], default_chart_options.merge(colors: ['red', 'black'])

h2 Power spectrum
- power_spectrum = {}
- signals_collection.signals(ck_noise: ck_noise).power_spectrum.each_pair do |k, val|
  - power_spectrum[human_hz_from_k(k)] = val
= area_chart power_spectrum, default_chart_options.merge(discrete: true, colors: ['orange'])



- filter_ck_list.each do |filter_ck|
  h2 Filter (from #{human_hz_from_k(filter_ck)})
  = line_chart [\
      {\
        name: 'filter + noise', \
        data: signals_collection.signals(ck_noise: ck_noise, from_ck_number: filter_ck).fourier\
      },\
      {\
        name: 'original',\
        data: signals_collection.signals.formated\
      },\
    ], default_chart_options.merge(colors: ['red', 'black'])

  h3 Filter reversed (from #{human_hz_from_k(filter_ck)})
  = line_chart [\
      {\
        name: 'original',\
        data: signals_collection.signals.formated\
      },\
      {\
        name: 'filter + noise', \
        data: signals_collection.signals(ck_noise: ck_noise, from_ck_number: filter_ck).fourier\
      }\
    ], default_chart_options.merge(colors: ['black', 'red'])

hr

signalai2/app/views/signals_collections/_noise_charts.html.slim
h1 Options
= form_tag url_for, method: :get do
  p
    = label_tag :ck_noise_interval, 'Hz noise interval'
    '
    = select_tag :ck_noise_interval_from, options_for_select((0..signals_collection.signals.n/2).map{|k| [human_hz_from_k(k), k] }, ck_noise_interval_from), class: :number_select
    '  -
    = select_tag :ck_noise_interval_till, options_for_select((0..signals_collection.signals.n/2).map{|k| [human_hz_from_k(k), k] }, ck_noise_interval_till)
  p
    = label_tag :noise_type, 'Noise type '
    ul
      li: label
        = radio_button_tag :noise_type, :random_scope, noise_type == 'random_scope'
        | Random with interval
        '
        = number_field_tag :min_random, min_random, placeholder: 'min random'
        '  -
        = number_field_tag :max_random, max_random, placeholder: 'max random'
      li: label
        = radio_button_tag :noise_type, :brownian, noise_type == 'brownian'
        | Brownian
  p
    | Ck filter
    .compact-container: table.filter-options
      - (0..signals_collection.signals.n/2).to_a.in_groups_of(5).each do |k_group|
        tr
          - k_group.each do |k|
            td: label
              - next if k.nil?
              = check_box_tag :"filter_ck_list[]", k, filter_ck_list.include?(k)
              - if filter_ck_list.include?(k)
                b= human_hz_from_k(k)
              - else
                = human_hz_from_k(k)

  p= submit_tag 'ok'
hr


/ h2 Original signals + noise
/ = line_chart signals_collection.signals(noise: noise).formated, colors: ['orange']

h2 Original signals + c<sub>k</sub> noise
.compact-container: table.CSSTableGenerator
  tr
    th Hz
    th Original
    th Noise
    th Noise + filter
  - original_cks = signals_collection.signals.all_ck
  - filter_cks = signals_collection.signals(ck_noise: ck_noise, from_ck_number: filter_ck_list.first).all_ck
  - signals_collection.signals(ck_noise: ck_noise).all_ck.each.with_index do |noise_ck, i|
    tr
      td[style='text-align: right;'] #{human_hz_from_k i}.
      td= original_cks[i]
      td= noise_ck
      td= filter_cks[i]

/ = render 'hz_noise_charts'

= render 'standart_noise_charts'

signalai2/app/views/signals_collections/_normal_charts.html.slim
/ h2 Original signals #{signals_collection.signals.formated.length}
/ = line_chart signals_collection.signals.formated, default_chart_options.merge(colors: ['black', 'red'])
br
hr
br

signalai2/app/views/signals_collections/_standart_noise_charts.html.slim
h2 Original signals + normal noise
= noise
= line_chart [\
    {\
      name: 'Fourier signalas',\
      data: signals_collection.signals.fourier\
    },\
    {\
      name: 'Originalus signalas',\
      data: signals_collection.signals.formated\
    }\
  ], default_chart_options.merge(colors: ['red', 'black'])

= line_chart [\
    {\
      name: 'Originalus signalas',\
      data: signals_collection.signals.formated\
    },\
    {\
      name: 'Fourier signalas',\
      data: signals_collection.signals.fourier\
    }\
  ], default_chart_options.merge(colors: ['black', 'red'])

= line_chart [\
    {\
      name: 'Užtriukšmintas signalas',\
      data: signals_collection.signals(noise: noise).fourier\
    },\
    {\
      name: 'Originalus signalas',\
      data: signals_collection.signals.formated\
    }\
  ], default_chart_options.merge(colors: ['red', 'black'])

h2 Power spectrum
- power_spectrum = {}
- signals_collection.signals(noise: noise).power_spectrum.each_pair do |k, val|
  - power_spectrum[human_hz_from_k(k)] = val
= area_chart power_spectrum, default_chart_options.merge(discrete: true, colors: ['orange'])

- filter_ck_list.each do |filter_ck|
  h2 Filter (from #{human_hz_from_k(filter_ck)})
  = line_chart [\
      {\
        name: 'filter + noise', \
        data: signals_collection.signals(noise: noise, from_ck_number: filter_ck).fourier\
      },\
      {\
        name: 'original',\
        data: signals_collection.signals.formated\
      },\
    ], default_chart_options.merge(colors: ['red', 'black'])

  h3 Filter reversed (from #{human_hz_from_k(filter_ck)})
  = line_chart [\
      {\
        name: 'original',\
        data: signals_collection.signals.formated\
      },\
      {\
        name: 'filter + noise', \
        data: signals_collection.signals(noise: noise, from_ck_number: filter_ck).fourier\
      }\
    ], default_chart_options.merge(colors: ['black', 'red'])

signalai2/app/views/signals_collections/chart.html.slim
h1= link_to signals_collection.url, signals_collection.url
hr

= render 'normal_charts'

= render 'noise_charts'

signalai2/app/views/signals_collections/edit.html.erb
<h1>Editing bitmap</h1>

<%= render 'form' %>

<%= link_to 'Show', @bitmap %> |
<%= link_to 'Back', bitmaps_path %>

signalai2/app/views/signals_collections/image.html.slim
h1= @bitmap.filename
h2= link_to @bitmap.url, @bitmap.url
.field
  = form_tag do
    = label_tag :r, 'r :'
    = text_field_tag :r, '0', class: 'r-input', style: 'width: 50px'
    br
    = label_tag :k, '  k :'
    = text_field_tag :k, '0', class: 'k-input', style: 'width: 50px'
    br
    = label_tag :resolution, '  resolution :'
    = text_field_tag :resolution, '800', class: 'resolution-input', style: 'width: 50px'
    br
    = label_tag :offset, '  offset :'
    = text_field_tag :offset, '0', class: 'offset-input', style: 'width: 50px'
    br
    = submit_tag 'generate', id: 'generate-svg'

= image_tag image_bitmap_path(format: :svg, r: params[:r]), id: 'graphic', "data-default-src" => image_bitmap_path(format: :svg)
'
= image_tag chart_bitmap_path(format: :svg), id: 'chart', "data-default-src" => chart_bitmap_path(format: :svg)

javascript:
  $('#generate-svg').on('click', function(e) {
    e.preventDefault();
    var r = $('.r-input').val();
    var k = $('.k-input').val();
    var res = $('.resolution-input').val();
    var offset = $('.offset-input').val();

    var query = "?r=" + r + "&k=" + k + "&res=" + res + "&offset=" + offset;

    var dafaultSrc = $('#graphic').data('default-src');
    $('#graphic').prop('src', dafaultSrc + query);

    dafaultSrc = $('#chart').data('default-src');
    $('#chart').prop('src', dafaultSrc + query);
  });

signalai2/app/views/signals_collections/index.html.slim
h1 Listing signals

table
  thead: tr
      th Filename
      th Signals number
      th
      th
      th
  tbody
    - signals_collections.each do |signals_collection|
      tr
        td= signals_collection.file_file_name
        td= signals_collection.signals_data.length
        td= link_to 'Chart', chart_signals_collection_path(signals_collection)
        td= link_to 'Edit', edit_signals_collection_path(signals_collection)
        td= link_to 'Destroy', signals_collection, method: :delete, data: { confirm: 'Are you sure?' }
br

= link_to 'New signal', new_signals_collection_path

signalai2/app/views/signals_collections/new.html.erb
<h1>New bitmap</h1>

<%= render 'form' %>

<%= link_to 'Back', signals_collections_path %>

signalai2/app/views/signals_collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @bitmap.filename %>
</p>

<p>
  <strong>Data:</strong>
  <%= @bitmap.data %>
</p>

<%= link_to 'Edit', edit_bitmap_path(@bitmap) %> |
<%= link_to 'Back', bitmaps_path %>